CREATE TABLE "squad" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "bio" text,
  "photo" varchar(255),
  "age" char(3) NOT NULL
);

CREATE TABLE "team" (
  "id" integer PRIMARY KEY,
  "squad_id" integer,
  "group_id" integer,
  "name" varchar(255) NOT NULL,
  "crest" varchar(255)
);

CREATE TABLE "group" (
  "id" integer PRIMARY KEY,
  "event_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "cup" boolean DEFAULT false,
  "age" char(3) NOT NULL
);

CREATE TABLE "group_table" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" integer NOT NULL,
  "team_id" integer NOT NULL,
  "position" integer NOT NULL,
  "played" integer NOT NULL DEFAULT 0,
  "won" integer NOT NULL DEFAULT 0,
  "drawn" integer NOT NULL DEFAULT 0,
  "lost" integer NOT NULL DEFAULT 0,
  "goals_for" integer NOT NULL DEFAULT 0,
  "goals_against" integer NOT NULL DEFAULT 0,
  "goal_difference" integer NOT NULL DEFAULT 0,
  "points" integer NOT NULL DEFAULT 0
);

CREATE TABLE "game" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_number" integer NOT NULL,
  "date" timestamp NOT NULL,
  "group_id" integer,
  "home_team_id" integer NOT NULL,
  "home_team_score" integer,
  "away_team_id" integer NOT NULL,
  "away_team_score" integer,
  "location" varchar(255)
);

CREATE TABLE "staff" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "title" varchar(255),
  "bio" text,
  "image" varchar(255),
  "email" varchar(255),
  "squad_id" integer
);

COMMENT ON TABLE "squad" IS 'A squad is a team or collection of players within the club
that take part in a league and or multiple cups. A squad
would appear as a team withing one or more groups.';

COMMENT ON TABLE "team" IS 'A team that is part of a group/league/cup. The same physical
team would have a team record per group to identify them';

COMMENT ON COLUMN "team"."id" IS 'Unique id generated by JPL or source';

COMMENT ON TABLE "group" IS 'A group can be a group, leage or cup. In JPL there are events to
signify age groups league then split into groups due to shear
numbers and geolocation';

COMMENT ON COLUMN "group"."id" IS 'JPL group id or other unique key from source';

COMMENT ON TABLE "staff" IS 'A member of staff at the club, be they a committee member,
coach or both. A staff member can optionally be related to
a team if they are a coach or manager. Staff with dual
roles have 2 staff records"';

ALTER TABLE "team" ADD FOREIGN KEY ("squad_id") REFERENCES "squad" ("id");

ALTER TABLE "team" ADD FOREIGN KEY ("group_id") REFERENCES "group" ("id");

ALTER TABLE "group_table" ADD FOREIGN KEY ("group_id") REFERENCES "group" ("id");

ALTER TABLE "group_table" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("id");

ALTER TABLE "game" ADD FOREIGN KEY ("group_id") REFERENCES "group" ("id");

ALTER TABLE "game" ADD FOREIGN KEY ("home_team_id") REFERENCES "team" ("id");

ALTER TABLE "game" ADD FOREIGN KEY ("away_team_id") REFERENCES "team" ("id");

ALTER TABLE "staff" ADD FOREIGN KEY ("squad_id") REFERENCES "squad" ("id");
