-- Add a new field to hold the group type
ALTER TABLE "group"
    ADD COLUMN group_type varchar(20) NOT NULL DEFAULT 'jpl_league';

-- update the group type value based on if the group is a cup or not
UPDATE "group"
    SET group_type = 'jpl_cup'
    WHERE cup = true;

UPDATE "group"
    SET group_type = 'jpl_league'
    WHERE cup = false;

-- Remove the column for cup
ALTER TABLE "group"
    DROP COLUMN cup;

-- Alter the team table so it generates an ID when one isn't provided
ALTER TABLE team
    ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Add groups and teams for hampshire cup
INSERT INTO "group" (id, name, age, group_type, event_id)
    VALUES
    (1001, 'Hampshire U12 Cup', 'U12', 'hampshire_cup', 0),
    (1002, 'Hampshire U13 Cup', 'U13', 'hampshire_cup', 0),
    (1003, 'Hampshire U15 Cup', 'U15', 'hampshire_cup', 0),
    (1004, 'Hampshire U16 Cup', 'U16', 'hampshire_cup', 0);

-- Add teams for hampshire cup
INSERT INTO team (id, name, group_id, squad_id)
    VALUES
    (1001, 'IGF Youth U12 Inspire Girls Academy', 1001,1),
    (1002, 'IGF Youth U13 Inspire Girls Academy', 1002, 2),
    (1003, 'IGF Youth U15 Inspire Girls Academy', 1003, 3),
    (1004, 'IGF Youth U16 Inspire Girls Academy', 1004, 4);
